version: "3.9"

services:
  # ---------- PostgreSQL ----------
  postgres:
    image: postgres:16
    container_name: infra-postgres-1
    environment:
      POSTGRES_DB: orderhub
      POSTGRES_USER: orderhub
      POSTGRES_PASSWORD: orderhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orderhub -d orderhub"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ---------- RabbitMQ (with management UI) ----------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: infra-rabbitmq-1
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ---------- MongoDB ----------
  mongo:
    image: mongo:7
    container_name: infra-mongo-1
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      # 'mongosh' is included in the official mongo image
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  rabbitmqdata:
  mongodata:
